export const stocks = [
  { label: "GameStop Corp - GME", Sector: "Gaming", Symbol: "GME" },
  { label: "A. O. Smith - AOS", Sector: "Industrials", Symbol: "AOS" },
  { label: "Abbott Laboratories - ABT", Sector: "Health Care", Symbol: "ABT" },
  { label: "AbbVie - ABBV", Sector: "Health Care", Symbol: "ABBV" },
  { label: "Abiomed - ABMD", Sector: "Health Care", Symbol: "ABMD" },
  { label: "Accenture - ACN", Sector: "Information Technology", Symbol: "ACN" },
  {
    label: "Activision Blizzard - ATVI",
    Sector: "Communication Services",
    Symbol: "ATVI",
  },
  { label: "ADM - ADM", Sector: "Consumer Staples", Symbol: "ADM" },
  { label: "Adobe - ADBE", Sector: "Information Technology", Symbol: "ADBE" },
  {
    label: "Advance Auto Parts - AAP",
    Sector: "Consumer Discretionary",
    Symbol: "AAP",
  },
  {
    label: "Advanced Micro Devices - AMD",
    Sector: "Information Technology",
    Symbol: "AMD",
  },
  { label: "AES Corp - AES", Sector: "Utilities", Symbol: "AES" },
  { label: "Aflac - AFL", Sector: "Financials", Symbol: "AFL" },
  { label: "Air Products & Chemicals - APD", Sector: "Materials", Symbol: "APD" },
  {
    label: "Akamai Technologies AKAM",
    Sector: "Information Technology",
    Symbol: "AKAM",
  },
  { label: "Alaska Air Group - ALK", Sector: "Industrials", Symbol: "ALK" },
  { label: "Albemarle Corporation - ALB", Sector: "Materials", Symbol: "ALB" },
  {
    label: "Alexandria Real Estate Equities - ARE",
    Sector: "Real Estate",
    Symbol: "ARE",
  },
  { label: "Align Technology - ALGN", Sector: "Health Care", Symbol: "ALGN" },
  { label: "Allegion - ALLE", Sector: "Industrials", Symbol: "ALLE" },
  { label: "Alliant Energy - LNT", Sector: "Utilities", Symbol: "LNT" },
  { label: "Allstate Corp - ALL", Sector: "Financials", Symbol: "ALL" },
  {
    label: "Alphabet (Class A) - GOOGL",
    Sector: "Communication Services",
    Symbol: "GOOGL",
  },
  {
    label: "Alphabet (Class C) - GOOG",
    Sector: "Communication Services",
    Symbol: "GOOG",
  },
  { label: "Altria Group - MO", Sector: "Consumer Staples", Symbol: "MO" },
  { label: "Amazon - AMZN", Sector: "Consumer Discretionary", Symbol: "AMZN" },
  { label: "Amcor - AMCR", Sector: "Materials", Symbol: "AMCR" },
  { label: "Ameren Corp - AEE", Sector: "Utilities", Symbol: "AEE" },
  { label: "American Airlines Group - AAL", Sector: "Industrials", Symbol: "AAL" },
  { label: "American Electric Power - AEP", Sector: "Utilities", Symbol: "AEP" },
  { label: "American Express - AXP", Sector: "Financials", Symbol: "AXP" },
  { label: "American International Group - AIG", Sector: "Financials", Symbol: "AIG" },
  { label: "American Tower - AMT", Sector: "Real Estate", Symbol: "AMT" },
  { label: "American Water Works - AWK", Sector: "Utilities", Symbol: "AWK" },
  { label: "Ameriprise Financial - AMP", Sector: "Financials", Symbol: "AMP" },
  { label: "AmerisourceBergen - ABC", Sector: "Health Care", Symbol: "ABC" },
  { label: "Ametek - AME", Sector: "Industrials", Symbol: "AME" },
  { label: "Amgen - AMGN", Sector: "Health Care", Symbol: "AMGN" },
  { label: "Amphenol - APH", Sector: "Information Technology", Symbol: "APH" },
  { label: "Analog Devices - ADI", Sector: "Information Technology", Symbol: "ADI" },
  { label: "Ansys - ANSS", Sector: "Information Technology", Symbol: "ANSS" },
  { label: "Anthem - ANTM", Sector: "Health Care", Symbol: "ANTM" },
  { label: "Aon - AON", Sector: "Financials", Symbol: "AON" },
  { label: "APA Corporation - APA", Sector: "Energy", Symbol: "APA" },
  { label: "Apple - AAPL", Sector: "Information Technology", Symbol: "AAPL" },
  {
    label: "Applied Materials - AMAT",
    Sector: "Information Technology",
    Symbol: "AMAT",
  },
  { label: "Aptiv - APTV", Sector: "Consumer Discretionary", Symbol: "APTV" },
  { label: "Arista Networks - ANET", Sector: "Information Technology", Symbol: "ANET" },
  { label: "Arthur J. Gallagher & Co. - AJG", Sector: "Financials", Symbol: "AJG" },
  { label: "Assurant - AIZ", Sector: "Financials", Symbol: "AIZ" },
  { label: "AT&T - T", Sector: "Communication Services", Symbol: "T" },
  { label: "Atmos Energy - ATO", Sector: "Utilities", Symbol: "ATO" },
  { label: "Autodesk - ADSK", Sector: "Information Technology", Symbol: "ADSK" },
  {
    label: "Automatic Data Processing - ADP",
    Sector: "Information Technology",
    Symbol: "ADP",
  },
  { label: "AutoZone - AZO", Sector: "Consumer Discretionary", Symbol: "AZO" },
  { label: "AvalonBay Communities - AVB", Sector: "Real Estate", Symbol: "AVB" },
  { label: "Avery Dennison - AVY", Sector: "Materials", Symbol: "AVY" },
  { label: "Baker Hughes - BKR", Sector: "Energy", Symbol: "BKR" },
  { label: "Ball Corp - BLL", Sector: "Materials", Symbol: "BLL" },
  { label: "Bank of America - BAC", Sector: "Financials", Symbol: "BAC" },
  {
    label: "Bath & Body Works Inc. - BBWI",
    Sector: "Consumer Discretionary",
    Symbol: "BBWI",
  },
  { label: "Baxter International - BAX", Sector: "Health Care", Symbol: "BAX" },
  { label: "Becton Dickinson - BDX", Sector: "Health Care", Symbol: "BDX" },
  { label: "Berkshire Hathaway - BRK.B", Sector: "Financials", Symbol: "BRK.B" },
  { label: "Best Buy - BBY", Sector: "Consumer Discretionary", Symbol: "BBY" },
  { label: "Bio-Rad Laboratories - BIO", Sector: "Health Care", Symbol: "BIO" },
  { label: "Bio-Techne - TECH", Sector: "Health Care", Symbol: "TECH" },
  { label: "Biogen - BIIB", Sector: "Health Care", Symbol: "BIIB" },
  { label: "BlackRock - BLK", Sector: "Financials", Symbol: "BLK" },
  { label: "BNY Mellon - BK", Sector: "Financials", Symbol: "BK" },
  { label: "Boeing - BA", Sector: "Industrials", Symbol: "BA" },
  {
    label: "Booking Holdings - BKNG",
    Sector: "Consumer Discretionary",
    Symbol: "BKNG",
  },
  { label: "BorgWarner - BWA", Sector: "Consumer Discretionary", Symbol: "BWA" },
  { label: "Boston Properties - BXP", Sector: "Real Estate", Symbol: "BXP" },
  { label: "Boston Scientific - BSX", Sector: "Health Care", Symbol: "BSX" },
  { label: "Bristol Myers Squibb - BMY", Sector: "Health Care", Symbol: "BMY" },
  { label: "Broadcom - AVGO", Sector: "Information Technology", Symbol: "AVGO" },
  {
    label: "Broadridge Financial Solutions - BR",
    Sector: "Information Technology",
    Symbol: "BR",
  },
  { label: "Brown & Brown - BRO", Sector: "Financials", Symbol: "BRO" },
  { label: "Brown\u2013Forman - BF.B", Sector: "Consumer Staples", Symbol: "BF.B" },
  { label: "C. H. Robinson - CHRW", Sector: "Industrials", Symbol: "CHRW" },
  {
    label: "Cadence Design Systems - CDNS",
    Sector: "Information Technology",
    Symbol: "CDNS",
  },
  {
    label: "Caesars Entertainment - CZR",
    Sector: "Consumer Discretionary",
    Symbol: "CZR",
  },
  { label: "Campbell Soup - CPB", Sector: "Consumer Staples", Symbol: "CPB" },
  { label: "Capital One Financial - COF", Sector: "Financials", Symbol: "COF" },
  { label: "Cardinal Health - CAH", Sector: "Health Care", Symbol: "CAH" },
  { label: "CarMax - KMX", Sector: "Consumer Discretionary", Symbol: "KMX" },
  {
    label: "Carnival Corporation - CCL",
    Sector: "Consumer Discretionary",
    Symbol: "CCL",
  },
  { label: "Carrier Global - CARR", Sector: "Industrials", Symbol: "CARR" },
  { label: "Catalent - CTLT", Sector: "Health Care", Symbol: "CTLT" },
  { label: "Caterpillar - CAT", Sector: "Industrials", Symbol: "CAT" },
  { label: "Cboe Global Markets - CBOE", Sector: "Financials", Symbol: "CBOE" },
  { label: "CBRE - CBRE", Sector: "Real Estate", Symbol: "CBRE" },
  { label: "CDW - CDW", Sector: "Information Technology", Symbol: "CDW" },
  { label: "Celanese - CE", Sector: "Materials", Symbol: "CE" },
  { label: "Centene Corporation - CNC", Sector: "Health Care", Symbol: "CNC" },
  { label: "CenterPoint Energy - CNP", Sector: "Utilities", Symbol: "CNP" },
  { label: "Ceridian - CDAY", Sector: "Information Technology", Symbol: "CDAY" },
  { label: "Cerner - CERN", Sector: "Health Care", Symbol: "CERN" },
  { label: "CF Industries - CF", Sector: "Materials", Symbol: "CF" },
  { label: "Charles River Laboratories - CRL", Sector: "Health Care", Symbol: "CRL" },
  { label: "Charles Schwab Corporation - SCHW", Sector: "Financials", Symbol: "SCHW" },
  {
    label: "Charter Communications - CHTR",
    Sector: "Communication Services",
    Symbol: "CHTR",
  },
  { label: "Chevron Corporation - CVX", Sector: "Energy", Symbol: "CVX" },
  {
    label: "Chipotle Mexican Grill - CMG",
    Sector: "Consumer Discretionary",
    Symbol: "CMG",
  },
  { label: "Chubb - CB", Sector: "Financials", Symbol: "CB" },
  { label: "Church & Dwight - CHD", Sector: "Consumer Staples", Symbol: "CHD" },
  { label: "Cigna - CI", Sector: "Health Care", Symbol: "CI" },
  { label: "Cincinnati Financial - CINF", Sector: "Financials", Symbol: "CINF" },
  { label: "Cintas Corporation - CTAS", Sector: "Industrials", Symbol: "CTAS" },
  { label: "Cisco Systems - CSCO", Sector: "Information Technology", Symbol: "CSCO" },
  { label: "Citigroup - C", Sector: "Financials", Symbol: "C" },
  { label: "Citizens Financial Group - CFG", Sector: "Financials", Symbol: "CFG" },
  { label: "Citrix Systems - CTXS", Sector: "Information Technology", Symbol: "CTXS" },
  { label: "Clorox - CLX", Sector: "Consumer Staples", Symbol: "CLX" },
  { label: "CME Group - CME", Sector: "Financials", Symbol: "CME" },
  { label: "CMS Energy - CMS", Sector: "Utilities", Symbol: "CMS" },
  { label: "Coca-Cola Company - KO", Sector: "Consumer Staples", Symbol: "KO" },
  {
    label: "Cognizant Technology Solutions - CTSH",
    Sector: "Information Technology",
    Symbol: "CTSH",
  },
  { label: "Colgate-Palmolive - CL", Sector: "Consumer Staples", Symbol: "CL" },
  { label: "Comcast - CMCSA", Sector: "Communication Services", Symbol: "CMCSA" },
  { label: "Comerica - CMA", Sector: "Financials", Symbol: "CMA" },
  { label: "Conagra Brands - CAG", Sector: "Consumer Staples", Symbol: "CAG" },
  { label: "ConocoPhillips - COP", Sector: "Energy", Symbol: "COP" },
  { label: "Consolidated Edison - ED", Sector: "Utilities", Symbol: "ED" },
  { label: "Constellation Brands - STZ", Sector: "Consumer Staples", Symbol: "STZ" },
  { label: "Copart - CPRT", Sector: "Industrials", Symbol: "CPRT" },
  { label: "Corning - GLW", Sector: "Information Technology", Symbol: "GLW" },
  { label: "Corteva - CTVA", Sector: "Materials", Symbol: "CTVA" },
  { label: "Costco - COST", Sector: "Consumer Staples", Symbol: "COST" },
  { label: "Coterra - CTRA", Sector: "Energy", Symbol: "CTRA" },
  { label: "Crown Castle - CCI", Sector: "Real Estate", Symbol: "CCI" },
  { label: "CSX - CSX", Sector: "Industrials", Symbol: "CSX" },
  { label: "Cummins - CMI", Sector: "Industrials", Symbol: "CMI" },
  { label: "CVS Health - CVS", Sector: "Health Care", Symbol: "CVS" },
  { label: "D. R. Horton - DHI", Sector: "Consumer Discretionary", Symbol: "DHI" },
  { label: "Danaher Corporation - DHR", Sector: "Health Care", Symbol: "DHR" },
  {
    label: "Darden Restaurants - DRI",
    Sector: "Consumer Discretionary",
    Symbol: "DRI",
  },
  { label: "DaVita - DVA", Sector: "Health Care", Symbol: "DVA" },
  { label: "Deere & Co. - DE", Sector: "Industrials", Symbol: "DE" },
  { label: "Delta Air Lines - DAL", Sector: "Industrials", Symbol: "DAL" },
  { label: "Dentsply Sirona - XRAY", Sector: "Health Care", Symbol: "XRAY" },
  { label: "Devon Energy - DVN", Sector: "Energy", Symbol: "DVN" },
  { label: "DexCom - DXCM", Sector: "Health Care", Symbol: "DXCM" },
  { label: "Diamondback Energy - FANG", Sector: "Energy", Symbol: "FANG" },
  { label: "Digital Realty Trust - DLR", Sector: "Real Estate", Symbol: "DLR" },
  { label: "Discover Financial Services - DFS", Sector: "Financials", Symbol: "DFS" },
  {
    label: "Discovery (Series A) - DISCA",
    Sector: "Communication Services",
    Symbol: "DISCA",
  },
  {
    label: "Discovery (Series C) - DISCK",
    Sector: "Communication Services",
    Symbol: "DISCK",
  },
  { label: "Dish Network - DISH", Sector: "Communication Services", Symbol: "DISH" },
  { label: "Dollar General - DG", Sector: "Consumer Discretionary", Symbol: "DG" },
  { label: "Dollar Tree - DLTR", Sector: "Consumer Discretionary", Symbol: "DLTR" },
  { label: "Dominion Energy - D", Sector: "Utilities", Symbol: "D" },
  { label: "Domino's Pizza - DPZ", Sector: "Consumer Discretionary", Symbol: "DPZ" },
  { label: "Dover Corporation - DOV", Sector: "Industrials", Symbol: "DOV" },
  { label: "Dow - DOW", Sector: "Materials", Symbol: "DOW" },
  { label: "DTE Energy - DTE", Sector: "Utilities", Symbol: "DTE" },
  { label: "Duke Energy - DUK", Sector: "Utilities", Symbol: "DUK" },
  { label: "Duke Realty Corp - DRE", Sector: "Real Estate", Symbol: "DRE" },
  { label: "DuPont - DD", Sector: "Materials", Symbol: "DD" },
  { label: "DXC Technology - DXC", Sector: "Information Technology", Symbol: "DXC" },
  { label: "Eastman Chemical - EMN", Sector: "Materials", Symbol: "EMN" },
  { label: "Eaton Corporation - ETN", Sector: "Industrials", Symbol: "ETN" },
  { label: "eBay - EBAY", Sector: "Consumer Discretionary", Symbol: "EBAY" },
  { label: "Ecolab - ECL", Sector: "Materials", Symbol: "ECL" },
  { label: "Edison International - EIX", Sector: "Utilities", Symbol: "EIX" },
  { label: "Edwards Lifesciences - EW", Sector: "Health Care", Symbol: "EW" },
  { label: "Electronic Arts - EA", Sector: "Communication Services", Symbol: "EA" },
  { label: "Eli Lilly & Co - LLY", Sector: "Health Care", Symbol: "LLY" },
  { label: "Emerson Electric Company - EMR", Sector: "Industrials", Symbol: "EMR" },
  { label: "Enphase Energy - ENPH", Sector: "Information Technology", Symbol: "ENPH" },
  { label: "Entergy - ETR", Sector: "Utilities", Symbol: "ETR" },
  { label: "EOG Resources - EOG", Sector: "Energy", Symbol: "EOG" },
  { label: "Equifax - EFX", Sector: "Industrials", Symbol: "EFX" },
  { label: "Equinix - EQIX", Sector: "Real Estate", Symbol: "EQIX" },
  { label: "Equity Residential - EQR", Sector: "Real Estate", Symbol: "EQR" },
  { label: "Essex Property Trust - ESS", Sector: "Real Estate", Symbol: "ESS" },
  {
    label: "Est\u00e9e Lauder Companies - EL",
    Sector: "Consumer Staples",
    Symbol: "EL",
  },
  { label: "Etsy - ETSY", Sector: "Consumer Discretionary", Symbol: "ETSY" },
  { label: "Everest Re - RE", Sector: "Financials", Symbol: "RE" },
  { label: "Evergy - EVRG", Sector: "Utilities", Symbol: "EVRG" },
  { label: "Eversource Energy - ES", Sector: "Utilities", Symbol: "ES" },
  { label: "Exelon - EXC", Sector: "Utilities", Symbol: "EXC" },
  { label: "Expedia Group - EXPE", Sector: "Consumer Discretionary", Symbol: "EXPE" },
  { label: "Expeditors - EXPD", Sector: "Industrials", Symbol: "EXPD" },
  { label: "Extra Space Storage - EXR", Sector: "Real Estate", Symbol: "EXR" },
  { label: "ExxonMobil - XOM", Sector: "Energy", Symbol: "XOM" },
  { label: "F5 Networks - FFIV", Sector: "Information Technology", Symbol: "FFIV" },
  { label: "Facebook - FB", Sector: "Communication Services", Symbol: "FB" },
  { label: "Fastenal - FAST", Sector: "Industrials", Symbol: "FAST" },
  {
    label: "Federal Realty Investment Trust - FRT",
    Sector: "Real Estate",
    Symbol: "FRT",
  },
  { label: "FedEx - FDX", Sector: "Industrials", Symbol: "FDX" },
  {
    label: "Fidelity National Information Services - FIS",
    Sector: "Information Technology",
    Symbol: "FIS",
  },
  { label: "Fifth Third Bancorp - FITB", Sector: "Financials", Symbol: "FITB" },
  { label: "First Republic Bank - FRC", Sector: "Financials", Symbol: "FRC" },
  { label: "FirstEnergy - FE", Sector: "Utilities", Symbol: "FE" },
  { label: "Fiserv - FISV", Sector: "Information Technology", Symbol: "FISV" },
  { label: "Fleetcor - FLT", Sector: "Information Technology", Symbol: "FLT" },
  { label: "FMC Corporation - FMC", Sector: "Materials", Symbol: "FMC" },
  { label: "Ford - F", Sector: "Consumer Discretionary", Symbol: "F" },
  { label: "Fortinet - FTNT", Sector: "Information Technology", Symbol: "FTNT" },
  { label: "Fortive - FTV", Sector: "Industrials", Symbol: "FTV" },
  {
    label: "Fortune Brands Home & Security - FBHS",
    Sector: "Industrials",
    Symbol: "FBHS",
  },
  {
    label: "Fox Corporation (Class A) - FOXA",
    Sector: "Communication Services",
    Symbol: "FOXA",
  },
  {
    label: "Fox Corporation (Class B) - FOX",
    Sector: "Communication Services",
    Symbol: "FOX",
  },
  { label: "Franklin Resources - BEN", Sector: "Financials", Symbol: "BEN" },
  { label: "Freeport-McMoRan - FCX", Sector: "Materials", Symbol: "FCX" },
  { label: "Gap - GPS", Sector: "Consumer Discretionary", Symbol: "GPS" },
  { label: "Garmin - GRMN", Sector: "Consumer Discretionary", Symbol: "GRMN" },
  { label: "Gartner - IT", Sector: "Information Technology", Symbol: "IT" },
  { label: "Generac Holdings - GNRC", Sector: "Industrials", Symbol: "GNRC" },
  { label: "General Dynamics - GD", Sector: "Industrials", Symbol: "GD" },
  { label: "General Electric - GE", Sector: "Industrials", Symbol: "GE" },
  { label: "General Mills - GIS", Sector: "Consumer Staples", Symbol: "GIS" },
  { label: "General Motors - GM", Sector: "Consumer Discretionary", Symbol: "GM" },
  { label: "Genuine Parts - GPC", Sector: "Consumer Discretionary", Symbol: "GPC" },
  { label: "Gilead Sciences - GILD", Sector: "Health Care", Symbol: "GILD" },
  { label: "Global Payments - GPN", Sector: "Information Technology", Symbol: "GPN" },
  { label: "Globe Life - GL", Sector: "Financials", Symbol: "GL" },
  { label: "Goldman Sachs - GS", Sector: "Financials", Symbol: "GS" },
  { label: "Halliburton - HAL", Sector: "Energy", Symbol: "HAL" },
  { label: "Hanesbrands - HBI", Sector: "Consumer Discretionary", Symbol: "HBI" },
  { label: "Hasbro - HAS", Sector: "Consumer Discretionary", Symbol: "HAS" },
  { label: "HCA Healthcare - HCA", Sector: "Health Care", Symbol: "HCA" },
  { label: "Healthpeak Properties - PEAK", Sector: "Real Estate", Symbol: "PEAK" },
  { label: "Henry Schein - HSIC", Sector: "Health Care", Symbol: "HSIC" },
  { label: "Hess Corporation - HES", Sector: "Energy", Symbol: "HES" },
  {
    label: "Hewlett Packard Enterprise - HPE",
    Sector: "Information Technology",
    Symbol: "HPE",
  },
  { label: "Hilton Worldwide - HLT", Sector: "Consumer Discretionary", Symbol: "HLT" },
  { label: "Hologic - HOLX", Sector: "Health Care", Symbol: "HOLX" },
  { label: "Home Depot - HD", Sector: "Consumer Discretionary", Symbol: "HD" },
  { label: "Honeywell - HON", Sector: "Industrials", Symbol: "HON" },
  { label: "Hormel - HRL", Sector: "Consumer Staples", Symbol: "HRL" },
  { label: "Host Hotels & Resorts - HST", Sector: "Real Estate", Symbol: "HST" },
  { label: "Howmet Aerospace - HWM", Sector: "Industrials", Symbol: "HWM" },
  { label: "HP - HPQ", Sector: "Information Technology", Symbol: "HPQ" },
  { label: "Humana - HUM", Sector: "Health Care", Symbol: "HUM" },
  { label: "Huntington Bancshares - HBAN", Sector: "Financials", Symbol: "HBAN" },
  {
    label: "Huntington Ingalls Industries - HII",
    Sector: "Industrials",
    Symbol: "HII",
  },
  { label: "IBM - IBM", Sector: "Information Technology", Symbol: "IBM" },
  { label: "IDEX Corporation - IEX", Sector: "Industrials", Symbol: "IEX" },
  { label: "Idexx Laboratories - IDXX", Sector: "Health Care", Symbol: "IDXX" },
  { label: "IHS Markit - INFO", Sector: "Industrials", Symbol: "INFO" },
  { label: "Illinois Tool Works - ITW", Sector: "Industrials", Symbol: "ITW" },
  { label: "Illumina - ILMN", Sector: "Health Care", Symbol: "ILMN" },
  { label: "Incyte - INCY", Sector: "Health Care", Symbol: "INCY" },
  { label: "Ingersoll Rand - IR", Sector: "Industrials", Symbol: "IR" },
  { label: "Intel - INTC", Sector: "Information Technology", Symbol: "INTC" },
  { label: "Intercontinental Exchange - ICE", Sector: "Financials", Symbol: "ICE" },
  {
    label: "International Flavors & Fragrances - IFF",
    Sector: "Materials",
    Symbol: "IFF",
  },
  { label: "International Paper - IP", Sector: "Materials", Symbol: "IP" },
  {
    label: "Interpublic Group - IPG",
    Sector: "Communication Services",
    Symbol: "IPG",
  },
  { label: "Intuit - INTU", Sector: "Information Technology", Symbol: "INTU" },
  { label: "Intuitive Surgical - ISRG", Sector: "Health Care", Symbol: "ISRG" },
  { label: "Invesco - IVZ", Sector: "Financials", Symbol: "IVZ" },
  { label: "IPG Photonics - IPGP", Sector: "Information Technology", Symbol: "IPGP" },
  { label: "IQVIA - IQV", Sector: "Health Care", Symbol: "IQV" },
  { label: "Iron Mountain - IRM", Sector: "Real Estate", Symbol: "IRM" },
  { label: "J. B. Hunt - JBHT", Sector: "Industrials", Symbol: "JBHT" },
  {
    label: "Jack Henry & Associates - JKHY",
    Sector: "Information Technology",
    Symbol: "JKHY",
  },
  { label: "Jacobs Engineering Group - J", Sector: "Industrials", Symbol: "J" },
  { label: "JM Smucker - SJM", Sector: "Consumer Staples", Symbol: "SJM" },
  { label: "Johnson & Johnson - JNJ", Sector: "Health Care", Symbol: "JNJ" },
  { label: "Johnson Controls - JCI", Sector: "Industrials", Symbol: "JCI" },
  { label: "JPMorgan Chase - JPM", Sector: "Financials", Symbol: "JPM" },
  {
    label: "Juniper Networks - JNPR",
    Sector: "Information Technology",
    Symbol: "JNPR",
  },
  { label: "Kansas City Southern - KSU", Sector: "Industrials", Symbol: "KSU" },
  { label: "Kellogg's - K", Sector: "Consumer Staples", Symbol: "K" },
  { label: "KeyCorp - KEY", Sector: "Financials", Symbol: "KEY" },
  {
    label: "Keysight Technologies - KEYS",
    Sector: "Information Technology",
    Symbol: "KEYS",
  },
  { label: "Kimberly-Clark - KMB", Sector: "Consumer Staples", Symbol: "KMB" },
  { label: "Kimco Realty - KIM", Sector: "Real Estate", Symbol: "KIM" },
  { label: "Kinder Morgan - KMI", Sector: "Energy", Symbol: "KMI" },
  { label: "KLA Corporation - KLAC", Sector: "Information Technology", Symbol: "KLAC" },
  { label: "Kraft Heinz - KHC", Sector: "Consumer Staples", Symbol: "KHC" },
  { label: "Kroger - KR", Sector: "Consumer Staples", Symbol: "KR" },
  { label: "L3Harris Technologies - LHX", Sector: "Industrials", Symbol: "LHX" },
  { label: "LabCorp - LH", Sector: "Health Care", Symbol: "LH" },
  { label: "Lam Research - LRCX", Sector: "Information Technology", Symbol: "LRCX" },
  { label: "Lamb Weston - LW", Sector: "Consumer Staples", Symbol: "LW" },
  { label: "Las Vegas Sands - LVS", Sector: "Consumer Discretionary", Symbol: "LVS" },
  { label: "Leggett & Platt - LEG", Sector: "Consumer Discretionary", Symbol: "LEG" },
  { label: "Leidos - LDOS", Sector: "Industrials", Symbol: "LDOS" },
  { label: "Lennar - LEN", Sector: "Consumer Discretionary", Symbol: "LEN" },
  { label: "Lincoln National - LNC", Sector: "Financials", Symbol: "LNC" },
  { label: "Linde - LIN", Sector: "Materials", Symbol: "LIN" },
  {
    label: "Live Nation Entertainment - LYV",
    Sector: "Communication Services",
    Symbol: "LYV",
  },
  { label: "LKQ Corporation - LKQ", Sector: "Consumer Discretionary", Symbol: "LKQ" },
  { label: "Lockheed Martin - LMT", Sector: "Industrials", Symbol: "LMT" },
  { label: "Loews Corporation - L", Sector: "Financials", Symbol: "L" },
  { label: "Lowe's - LOW", Sector: "Consumer Discretionary", Symbol: "LOW" },
  {
    label: "Lumen Technologies - LUMN",
    Sector: "Communication Services",
    Symbol: "LUMN",
  },
  { label: "LyondellBasell - LYB", Sector: "Materials", Symbol: "LYB" },
  { label: "M&T Bank - MTB", Sector: "Financials", Symbol: "MTB" },
  { label: "Marathon Oil - MRO", Sector: "Energy", Symbol: "MRO" },
  { label: "Marathon Petroleum - MPC", Sector: "Energy", Symbol: "MPC" },
  { label: "MarketAxess - MKTX", Sector: "Financials", Symbol: "MKTX" },
  {
    label: "Marriott International - MAR",
    Sector: "Consumer Discretionary",
    Symbol: "MAR",
  },
  { label: "Marsh & McLennan - MMC", Sector: "Financials", Symbol: "MMC" },
  { label: "Martin Marietta Materials - MLM", Sector: "Materials", Symbol: "MLM" },
  { label: "Masco - MAS", Sector: "Industrials", Symbol: "MAS" },
  { label: "Mastercard - MA", Sector: "Information Technology", Symbol: "MA" },
  { label: "Match Group - MTCH", Sector: "Communication Services", Symbol: "MTCH" },
  { label: "McCormick & Company - MKC", Sector: "Consumer Staples", Symbol: "MKC" },
  { label: "McDonald's - MCD", Sector: "Consumer Discretionary", Symbol: "MCD" },
  { label: "McKesson Corporation - MCK", Sector: "Health Care", Symbol: "MCK" },
  { label: "Medtronic - MDT", Sector: "Health Care", Symbol: "MDT" },
  { label: "Merck & Co. - MRK", Sector: "Health Care", Symbol: "MRK" },
  { label: "MetLife - MET", Sector: "Financials", Symbol: "MET" },
  { label: "Mettler Toledo - MTD", Sector: "Health Care", Symbol: "MTD" },
  {
    label: "MGM Resorts International - MGM",
    Sector: "Consumer Discretionary",
    Symbol: "MGM",
  },
  {
    label: "Microchip Technology - MCHP",
    Sector: "Information Technology",
    Symbol: "MCHP",
  },
  { label: "Micron Technology - MU", Sector: "Information Technology", Symbol: "MU" },
  { label: "Microsoft - MSFT", Sector: "Information Technology", Symbol: "MSFT" },
  { label: "Mid-America Apartments - MAA", Sector: "Real Estate", Symbol: "MAA" },
  { label: "Moderna - MRNA", Sector: "Health Care", Symbol: "MRNA" },
  {
    label: "Mohawk Industries - MHK",
    Sector: "Consumer Discretionary",
    Symbol: "MHK",
  },
  {
    label: "Molson Coors Beverage Company - TAP",
    Sector: "Consumer Staples",
    Symbol: "TAP",
  },
  {
    label: "Mondelez International - MDLZ",
    Sector: "Consumer Staples",
    Symbol: "MDLZ",
  },
  {
    label: "Monolithic Power Systems - MPWR",
    Sector: "Information Technology",
    Symbol: "MPWR",
  },
  { label: "Monster Beverage - MNST", Sector: "Consumer Staples", Symbol: "MNST" },
  { label: "Moody's Corporation - MCO", Sector: "Financials", Symbol: "MCO" },
  { label: "Morgan Stanley - MS", Sector: "Financials", Symbol: "MS" },
  {
    label: "Motorola Solutions - MSI",
    Sector: "Information Technology",
    Symbol: "MSI",
  },
  { label: "MSCI - MSCI", Sector: "Financials", Symbol: "MSCI" },
  { label: "Nasdaq - NDAQ", Sector: "Financials", Symbol: "NDAQ" },
  { label: "NetApp - NTAP", Sector: "Information Technology", Symbol: "NTAP" },
  { label: "Netflix - NFLX", Sector: "Communication Services", Symbol: "NFLX" },
  { label: "Newell Brands - NWL", Sector: "Consumer Discretionary", Symbol: "NWL" },
  { label: "Newmont - NEM", Sector: "Materials", Symbol: "NEM" },
  {
    label: "News Corp (Class A) - NWSA",
    Sector: "Communication Services",
    Symbol: "NWSA",
  },
  {
    label: "News Corp (Class B) - NWS",
    Sector: "Communication Services",
    Symbol: "NWS",
  },
  { label: "NextEra Energy - NEE", Sector: "Utilities", Symbol: "NEE" },
  { label: "Nielsen Holdings - NLSN", Sector: "Industrials", Symbol: "NLSN" },
  { label: "Nike - NKE", Sector: "Consumer Discretionary", Symbol: "NKE" },
  { label: "NiSource - NI", Sector: "Utilities", Symbol: "NI" },
  { label: "Norfolk Southern - NSC", Sector: "Industrials", Symbol: "NSC" },
  { label: "Northern Trust - NTRS", Sector: "Financials", Symbol: "NTRS" },
  { label: "Northrop Grumman - NOC", Sector: "Industrials", Symbol: "NOC" },
  { label: "NortonLifeLock - NLOK", Sector: "Information Technology", Symbol: "NLOK" },
  {
    label: "Norwegian Cruise Line Holdings - NCLH",
    Sector: "Consumer Discretionary",
    Symbol: "NCLH",
  },
  { label: "NRG Energy - NRG", Sector: "Utilities", Symbol: "NRG" },
  { label: "Nucor - NUE", Sector: "Materials", Symbol: "NUE" },
  { label: "Nvidia - NVDA", Sector: "Information Technology", Symbol: "NVDA" },
  { label: "NVR - NVR", Sector: "Consumer Discretionary", Symbol: "NVR" },
  { label: "NXP - NXPI", Sector: "Information Technology", Symbol: "NXPI" },
  {
    label: "O'Reilly Automotive - ORLY",
    Sector: "Consumer Discretionary",
    Symbol: "ORLY",
  },
  { label: "Occidental Petroleum - OXY", Sector: "Energy", Symbol: "OXY" },
  { label: "Old Dominion Freight Line - ODFL", Sector: "Industrials", Symbol: "ODFL" },
  { label: "Omnicom Group - OMC", Sector: "Communication Services", Symbol: "OMC" },
  { label: "Oneok - OKE", Sector: "Energy", Symbol: "OKE" },
  { label: "Oracle - ORCL", Sector: "Information Technology", Symbol: "ORCL" },
  { label: "Organon & Co. - OGN", Sector: "Health Care", Symbol: "OGN" },
  { label: "Otis Worldwide - OTIS", Sector: "Industrials", Symbol: "OTIS" },
  { label: "Paccar - PCAR", Sector: "Industrials", Symbol: "PCAR" },
  {
    label: "Packaging Corporation of America - PKG",
    Sector: "Materials",
    Symbol: "PKG",
  },
  { label: "Parker-Hannifin - PH", Sector: "Industrials", Symbol: "PH" },
  { label: "Paychex - PAYX", Sector: "Information Technology", Symbol: "PAYX" },
  { label: "Paycom - PAYC", Sector: "Information Technology", Symbol: "PAYC" },
  { label: "PayPal - PYPL", Sector: "Information Technology", Symbol: "PYPL" },
  {
    label: "Penn National Gaming - PENN",
    Sector: "Consumer Discretionary",
    Symbol: "PENN",
  },
  { label: "Pentair - PNR", Sector: "Industrials", Symbol: "PNR" },
  { label: "People's United Financial - PBCT", Sector: "Financials", Symbol: "PBCT" },
  { label: "PepsiCo - PEP", Sector: "Consumer Staples", Symbol: "PEP" },
  { label: "PerkinElmer - PKI", Sector: "Health Care", Symbol: "PKI" },
  { label: "Pfizer - PFE", Sector: "Health Care", Symbol: "PFE" },
  {
    label: "Philip Morris International - PM",
    Sector: "Consumer Staples",
    Symbol: "PM",
  },
  { label: "Phillips 66 - PSX", Sector: "Energy", Symbol: "PSX" },
  { label: "Pinnacle West Capital - PNW", Sector: "Utilities", Symbol: "PNW" },
  { label: "Pioneer Natural Resources - PXD", Sector: "Energy", Symbol: "PXD" },
  { label: "PNC Financial Services - PNC", Sector: "Financials", Symbol: "PNC" },
  {
    label: "Pool Corporation - POOL",
    Sector: "Consumer Discretionary",
    Symbol: "POOL",
  },
  { label: "PPG Industries - PPG", Sector: "Materials", Symbol: "PPG" },
  { label: "PPL - PPL", Sector: "Utilities", Symbol: "PPL" },
  { label: "Principal Financial Group - PFG", Sector: "Financials", Symbol: "PFG" },
  { label: "Procter & Gamble - PG", Sector: "Consumer Staples", Symbol: "PG" },
  { label: "Progressive Corporation - PGR", Sector: "Financials", Symbol: "PGR" },
  { label: "Prologis - PLD", Sector: "Real Estate", Symbol: "PLD" },
  { label: "Prudential Financial - PRU", Sector: "Financials", Symbol: "PRU" },
  { label: "PTC - PTC", Sector: "Information Technology", Symbol: "PTC" },
  {
    label: "Public Service Enterprise Group - PEG",
    Sector: "Utilities",
    Symbol: "PEG",
  },
  { label: "Public Storage - PSA", Sector: "Real Estate", Symbol: "PSA" },
  { label: "PulteGroup - PHM", Sector: "Consumer Discretionary", Symbol: "PHM" },
  { label: "PVH - PVH", Sector: "Consumer Discretionary", Symbol: "PVH" },
  { label: "Qorvo - QRVO", Sector: "Information Technology", Symbol: "QRVO" },
  { label: "Qualcomm - QCOM", Sector: "Information Technology", Symbol: "QCOM" },
  { label: "Quanta Services - PWR", Sector: "Industrials", Symbol: "PWR" },
  { label: "Quest Diagnostics - DGX", Sector: "Health Care", Symbol: "DGX" },
  {
    label: "Ralph Lauren Corporation - RL",
    Sector: "Consumer Discretionary",
    Symbol: "RL",
  },
  { label: "Raymond James Financial - RJF", Sector: "Financials", Symbol: "RJF" },
  { label: "Raytheon Technologies - RTX", Sector: "Industrials", Symbol: "RTX" },
  { label: "Realty Income Corporation - O", Sector: "Real Estate", Symbol: "O" },
  { label: "Regency Centers - REG", Sector: "Real Estate", Symbol: "REG" },
  { label: "Regeneron Pharmaceuticals - REGN", Sector: "Health Care", Symbol: "REGN" },
  { label: "Regions Financial Corporation - RF", Sector: "Financials", Symbol: "RF" },
  { label: "Republic Services - RSG", Sector: "Industrials", Symbol: "RSG" },
  { label: "ResMed - RMD", Sector: "Health Care", Symbol: "RMD" },
  { label: "Robert Half International - RHI", Sector: "Industrials", Symbol: "RHI" },
  { label: "Rockwell Automation - ROK", Sector: "Industrials", Symbol: "ROK" },
  { label: "Rollins - ROL", Sector: "Industrials", Symbol: "ROL" },
  { label: "Roper Technologies - ROP", Sector: "Industrials", Symbol: "ROP" },
  { label: "Ross Stores - ROST", Sector: "Consumer Discretionary", Symbol: "ROST" },
  {
    label: "Royal Caribbean Group - RCL",
    Sector: "Consumer Discretionary",
    Symbol: "RCL",
  },
  { label: "S&P Global - SPGI", Sector: "Financials", Symbol: "SPGI" },
  { label: "Salesforce - CRM", Sector: "Information Technology", Symbol: "CRM" },
  { label: "SBA Communications - SBAC", Sector: "Real Estate", Symbol: "SBAC" },
  { label: "Schlumberger - SLB", Sector: "Energy", Symbol: "SLB" },
  {
    label: "Seagate Technology - STX",
    Sector: "Information Technology",
    Symbol: "STX",
  },
  { label: "Sealed Air - SEE", Sector: "Materials", Symbol: "SEE" },
  { label: "Sempra Energy - SRE", Sector: "Utilities", Symbol: "SRE" },
  { label: "ServiceNow - NOW", Sector: "Information Technology", Symbol: "NOW" },
  { label: "Sherwin-Williams - SHW", Sector: "Materials", Symbol: "SHW" },
  { label: "Simon Property Group - SPG", Sector: "Real Estate", Symbol: "SPG" },
  {
    label: "Skyworks Solutions - SWKS",
    Sector: "Information Technology",
    Symbol: "SWKS",
  },
  { label: "Snap-on - SNA", Sector: "Industrials", Symbol: "SNA" },
  { label: "Southern Company - SO", Sector: "Utilities", Symbol: "SO" },
  { label: "Southwest Airlines - LUV", Sector: "Industrials", Symbol: "LUV" },
  { label: "Stanley Black & Decker - SWK", Sector: "Industrials", Symbol: "SWK" },
  { label: "Starbucks - SBUX", Sector: "Consumer Discretionary", Symbol: "SBUX" },
  { label: "State Street Corporation - STT", Sector: "Financials", Symbol: "STT" },
  { label: "Steris - STE", Sector: "Health Care", Symbol: "STE" },
  { label: "Stryker Corporation - SYK", Sector: "Health Care", Symbol: "SYK" },
  { label: "SVB Financial - SIVB", Sector: "Financials", Symbol: "SIVB" },
  { label: "Synchrony Financial - SYF", Sector: "Financials", Symbol: "SYF" },
  { label: "Synopsys - SNPS", Sector: "Information Technology", Symbol: "SNPS" },
  { label: "Sysco - SYY", Sector: "Consumer Staples", Symbol: "SYY" },
  { label: "T-Mobile US - TMUS", Sector: "Communication Services", Symbol: "TMUS" },
  { label: "T. Rowe Price - TROW", Sector: "Financials", Symbol: "TROW" },
  {
    label: "Take-Two Interactive - TTWO",
    Sector: "Communication Services",
    Symbol: "TTWO",
  },
  { label: "Tapestry - TPR", Sector: "Consumer Discretionary", Symbol: "TPR" },
  {
    label: "Target Corporation - TGT",
    Sector: "Consumer Discretionary",
    Symbol: "TGT",
  },
  { label: "TE Connectivity - TEL", Sector: "Information Technology", Symbol: "TEL" },
  { label: "Teledyne Technologies - TDY", Sector: "Industrials", Symbol: "TDY" },
  { label: "Teleflex - TFX", Sector: "Health Care", Symbol: "TFX" },
  { label: "Teradyne - TER", Sector: "Information Technology", Symbol: "TER" },
  { label: "Tesla - TSLA", Sector: "Consumer Discretionary", Symbol: "TSLA" },
  {
    label: "Texas Instruments - TXN",
    Sector: "Information Technology",
    Symbol: "TXN",
  },
  { label: "Textron - TXT", Sector: "Industrials", Symbol: "TXT" },
  { label: "The Cooper Companies - COO", Sector: "Health Care", Symbol: "COO" },
  { label: "The Hartford - HIG", Sector: "Financials", Symbol: "HIG" },
  { label: "The Hershey Company - HSY", Sector: "Consumer Staples", Symbol: "HSY" },
  { label: "The Mosaic Company - MOS", Sector: "Materials", Symbol: "MOS" },
  { label: "The Travelers Companies - TRV", Sector: "Financials", Symbol: "TRV" },
  {
    label: "The Walt Disney Company - DIS",
    Sector: "Communication Services",
    Symbol: "DIS",
  },
  { label: "Thermo Fisher Scientific - TMO", Sector: "Health Care", Symbol: "TMO" },
  { label: "TJX Companies - TJX", Sector: "Consumer Discretionary", Symbol: "TJX" },
  {
    label: "Tractor Supply Company - TSCO",
    Sector: "Consumer Discretionary",
    Symbol: "TSCO",
  },
  { label: "Trane Technologies - TT", Sector: "Industrials", Symbol: "TT" },
  { label: "TransDigm Group - TDG", Sector: "Industrials", Symbol: "TDG" },
  { label: "Trimble - TRMB", Sector: "Information Technology", Symbol: "TRMB" },
  { label: "Truist Financial - TFC", Sector: "Financials", Symbol: "TFC" },
  { label: "Twitter - TWTR", Sector: "Communication Services", Symbol: "TWTR" },
  {
    label: "Tyler Technologies - TYL",
    Sector: "Information Technology",
    Symbol: "TYL",
  },
  { label: "Tyson Foods - TSN", Sector: "Consumer Staples", Symbol: "TSN" },
  { label: "U.S. Bancorp - USB", Sector: "Financials", Symbol: "USB" },
  { label: "UDR - UDR", Sector: "Real Estate", Symbol: "UDR" },
  { label: "Ulta Beauty - ULTA", Sector: "Consumer Discretionary", Symbol: "ULTA" },
  {
    label: "Under Armour (Class A) - UAA",
    Sector: "Consumer Discretionary",
    Symbol: "UAA",
  },
  {
    label: "Under Armour (Class C) - UA",
    Sector: "Consumer Discretionary",
    Symbol: "UA",
  },
  { label: "Union Pacific - UNP", Sector: "Industrials", Symbol: "UNP" },
  { label: "United Airlines - UAL", Sector: "Industrials", Symbol: "UAL" },
  { label: "United Parcel Service - UPS", Sector: "Industrials", Symbol: "UPS" },
  { label: "United Rentals - URI", Sector: "Industrials", Symbol: "URI" },
  { label: "UnitedHealth Group - UNH", Sector: "Health Care", Symbol: "UNH" },
  { label: "Universal Health Services - UHS", Sector: "Health Care", Symbol: "UHS" },
  { label: "Valero Energy - VLO", Sector: "Energy", Symbol: "VLO" },
  { label: "Ventas - VTR", Sector: "Real Estate", Symbol: "VTR" },
  { label: "Verisign - VRSN", Sector: "Information Technology", Symbol: "VRSN" },
  { label: "Verisk Analytics - VRSK", Sector: "Industrials", Symbol: "VRSK" },
  {
    label: "Verizon Communications - VZ",
    Sector: "Communication Services",
    Symbol: "VZ",
  },
  { label: "Vertex Pharmaceuticals - VRTX", Sector: "Health Care", Symbol: "VRTX" },
  { label: "VF Corporation - VFC", Sector: "Consumer Discretionary", Symbol: "VFC" },
  { label: "ViacomCBS - VIAC", Sector: "Communication Services", Symbol: "VIAC" },
  { label: "Viatris - VTRS", Sector: "Health Care", Symbol: "VTRS" },
  { label: "Visa - V", Sector: "Information Technology", Symbol: "V" },
  { label: "Vornado Realty Trust - VNO", Sector: "Real Estate", Symbol: "VNO" },
  { label: "Vulcan Materials - VMC", Sector: "Materials", Symbol: "VMC" },
  { label: "W. R. Berkley Corporation - WRB", Sector: "Financials", Symbol: "WRB" },
  { label: "W. W. Grainger - GWW", Sector: "Industrials", Symbol: "GWW" },
  { label: "Wabtec - WAB", Sector: "Industrials", Symbol: "WAB" },
  {
    label: "Walgreens Boots Alliance - WBA",
    Sector: "Consumer Staples",
    Symbol: "WBA",
  },
  { label: "Walmart - WMT", Sector: "Consumer Staples", Symbol: "WMT" },
  { label: "Waste Management - WM", Sector: "Industrials", Symbol: "WM" },
  { label: "Waters Corporation - WAT", Sector: "Health Care", Symbol: "WAT" },
  { label: "WEC Energy Group - WEC", Sector: "Utilities", Symbol: "WEC" },
  { label: "Wells Fargo - WFC", Sector: "Financials", Symbol: "WFC" },
  { label: "Welltower - WELL", Sector: "Real Estate", Symbol: "WELL" },
  {
    label: "West Pharmaceutical Services - WST",
    Sector: "Health Care",
    Symbol: "WST",
  },
  { label: "Western Digital - WDC", Sector: "Information Technology", Symbol: "WDC" },
  { label: "Western Union - WU", Sector: "Information Technology", Symbol: "WU" },
  { label: "WestRock - WRK", Sector: "Materials", Symbol: "WRK" },
  { label: "Weyerhaeuser - WY", Sector: "Real Estate", Symbol: "WY" },
  {
    label: "Whirlpool Corporation - WHR",
    Sector: "Consumer Discretionary",
    Symbol: "WHR",
  },
  { label: "Williams Companies - WMB", Sector: "Energy", Symbol: "WMB" },
  { label: "Willis Towers Watson - WLTW", Sector: "Financials", Symbol: "WLTW" },
  { label: "Wynn Resorts - WYNN", Sector: "Consumer Discretionary", Symbol: "WYNN" },
  { label: "Xcel Energy - XEL", Sector: "Utilities", Symbol: "XEL" },
  { label: "Xilinx - XLNX", Sector: "Information Technology", Symbol: "XLNX" },
  { label: "Xylem - XYL", Sector: "Industrials", Symbol: "XYL" },
  { label: "Yum! Brands - YUM", Sector: "Consumer Discretionary", Symbol: "YUM" },
  {
    label: "Zebra Technologies - ZBRA",
    Sector: "Information Technology",
    Symbol: "ZBRA",
  },
  { label: "Zimmer Biomet - ZBH", Sector: "Health Care", Symbol: "ZBH" },
  { label: "Zions Bancorp - ZION", Sector: "Financials", Symbol: "ZION" },
  { label: "Zoetis - ZTS", Sector: "Health Care", Symbol: "ZTS" },
];
