export const stocks = [
  { label: "3M", Sector: "Industrials", Symbol: "MMM" },
  { label: "A. O. Smith", Sector: "Industrials", Symbol: "AOS" },
  { label: "Abbott Laboratories", Sector: "Health Care", Symbol: "ABT" },
  { label: "AbbVie", Sector: "Health Care", Symbol: "ABBV" },
  { label: "Abiomed", Sector: "Health Care", Symbol: "ABMD" },
  { label: "Accenture", Sector: "Information Technology", Symbol: "ACN" },
  {
    label: "Activision Blizzard",
    Sector: "Communication Services",
    Symbol: "ATVI",
  },
  { label: "ADM", Sector: "Consumer Staples", Symbol: "ADM" },
  { label: "Adobe", Sector: "Information Technology", Symbol: "ADBE" },
  {
    label: "Advance Auto Parts",
    Sector: "Consumer Discretionary",
    Symbol: "AAP",
  },
  {
    label: "Advanced Micro Devices",
    Sector: "Information Technology",
    Symbol: "AMD",
  },
  { label: "AES Corp", Sector: "Utilities", Symbol: "AES" },
  { label: "Aflac", Sector: "Financials", Symbol: "AFL" },
  { label: "Agilent Technologies", Sector: "Health Care", Symbol: "A" },
  { label: "Air Products & Chemicals", Sector: "Materials", Symbol: "APD" },
  {
    label: "Akamai Technologies",
    Sector: "Information Technology",
    Symbol: "AKAM",
  },
  { label: "Alaska Air Group", Sector: "Industrials", Symbol: "ALK" },
  { label: "Albemarle Corporation", Sector: "Materials", Symbol: "ALB" },
  {
    label: "Alexandria Real Estate Equities",
    Sector: "Real Estate",
    Symbol: "ARE",
  },
  { label: "Align Technology", Sector: "Health Care", Symbol: "ALGN" },
  { label: "Allegion", Sector: "Industrials", Symbol: "ALLE" },
  { label: "Alliant Energy", Sector: "Utilities", Symbol: "LNT" },
  { label: "Allstate Corp", Sector: "Financials", Symbol: "ALL" },
  {
    label: "Alphabet (Class A)",
    Sector: "Communication Services",
    Symbol: "GOOGL",
  },
  {
    label: "Alphabet (Class C)",
    Sector: "Communication Services",
    Symbol: "GOOG",
  },
  { label: "Altria Group", Sector: "Consumer Staples", Symbol: "MO" },
  { label: "Amazon", Sector: "Consumer Discretionary", Symbol: "AMZN" },
  { label: "Amcor", Sector: "Materials", Symbol: "AMCR" },
  { label: "Ameren Corp", Sector: "Utilities", Symbol: "AEE" },
  { label: "American Airlines Group", Sector: "Industrials", Symbol: "AAL" },
  { label: "American Electric Power", Sector: "Utilities", Symbol: "AEP" },
  { label: "American Express", Sector: "Financials", Symbol: "AXP" },
  { label: "American International Group", Sector: "Financials", Symbol: "AIG" },
  { label: "American Tower", Sector: "Real Estate", Symbol: "AMT" },
  { label: "American Water Works", Sector: "Utilities", Symbol: "AWK" },
  { label: "Ameriprise Financial", Sector: "Financials", Symbol: "AMP" },
  { label: "AmerisourceBergen", Sector: "Health Care", Symbol: "ABC" },
  { label: "Ametek", Sector: "Industrials", Symbol: "AME" },
  { label: "Amgen", Sector: "Health Care", Symbol: "AMGN" },
  { label: "Amphenol", Sector: "Information Technology", Symbol: "APH" },
  { label: "Analog Devices", Sector: "Information Technology", Symbol: "ADI" },
  { label: "Ansys", Sector: "Information Technology", Symbol: "ANSS" },
  { label: "Anthem", Sector: "Health Care", Symbol: "ANTM" },
  { label: "Aon", Sector: "Financials", Symbol: "AON" },
  { label: "APA Corporation", Sector: "Energy", Symbol: "APA" },
  { label: "Apple", Sector: "Information Technology", Symbol: "AAPL" },
  {
    label: "Applied Materials",
    Sector: "Information Technology",
    Symbol: "AMAT",
  },
  { label: "Aptiv", Sector: "Consumer Discretionary", Symbol: "APTV" },
  { label: "Arista Networks", Sector: "Information Technology", Symbol: "ANET" },
  { label: "Arthur J. Gallagher & Co.", Sector: "Financials", Symbol: "AJG" },
  { label: "Assurant", Sector: "Financials", Symbol: "AIZ" },
  { label: "AT&T", Sector: "Communication Services", Symbol: "T" },
  { label: "Atmos Energy", Sector: "Utilities", Symbol: "ATO" },
  { label: "Autodesk", Sector: "Information Technology", Symbol: "ADSK" },
  {
    label: "Automatic Data Processing",
    Sector: "Information Technology",
    Symbol: "ADP",
  },
  { label: "AutoZone", Sector: "Consumer Discretionary", Symbol: "AZO" },
  { label: "AvalonBay Communities", Sector: "Real Estate", Symbol: "AVB" },
  { label: "Avery Dennison", Sector: "Materials", Symbol: "AVY" },
  { label: "Baker Hughes", Sector: "Energy", Symbol: "BKR" },
  { label: "Ball Corp", Sector: "Materials", Symbol: "BLL" },
  { label: "Bank of America", Sector: "Financials", Symbol: "BAC" },
  {
    label: "Bath & Body Works Inc.",
    Sector: "Consumer Discretionary",
    Symbol: "BBWI",
  },
  { label: "Baxter International", Sector: "Health Care", Symbol: "BAX" },
  { label: "Becton Dickinson", Sector: "Health Care", Symbol: "BDX" },
  { label: "Berkshire Hathaway", Sector: "Financials", Symbol: "BRK.B" },
  { label: "Best Buy", Sector: "Consumer Discretionary", Symbol: "BBY" },
  { label: "Bio-Rad Laboratories", Sector: "Health Care", Symbol: "BIO" },
  { label: "Bio-Techne", Sector: "Health Care", Symbol: "TECH" },
  { label: "Biogen", Sector: "Health Care", Symbol: "BIIB" },
  { label: "BlackRock", Sector: "Financials", Symbol: "BLK" },
  { label: "BNY Mellon", Sector: "Financials", Symbol: "BK" },
  { label: "Boeing", Sector: "Industrials", Symbol: "BA" },
  {
    label: "Booking Holdings",
    Sector: "Consumer Discretionary",
    Symbol: "BKNG",
  },
  { label: "BorgWarner", Sector: "Consumer Discretionary", Symbol: "BWA" },
  { label: "Boston Properties", Sector: "Real Estate", Symbol: "BXP" },
  { label: "Boston Scientific", Sector: "Health Care", Symbol: "BSX" },
  { label: "Bristol Myers Squibb", Sector: "Health Care", Symbol: "BMY" },
  { label: "Broadcom", Sector: "Information Technology", Symbol: "AVGO" },
  {
    label: "Broadridge Financial Solutions",
    Sector: "Information Technology",
    Symbol: "BR",
  },
  { label: "Brown & Brown", Sector: "Financials", Symbol: "BRO" },
  { label: "Brown\u2013Forman", Sector: "Consumer Staples", Symbol: "BF.B" },
  { label: "C. H. Robinson", Sector: "Industrials", Symbol: "CHRW" },
  {
    label: "Cadence Design Systems",
    Sector: "Information Technology",
    Symbol: "CDNS",
  },
  {
    label: "Caesars Entertainment",
    Sector: "Consumer Discretionary",
    Symbol: "CZR",
  },
  { label: "Campbell Soup", Sector: "Consumer Staples", Symbol: "CPB" },
  { label: "Capital One Financial", Sector: "Financials", Symbol: "COF" },
  { label: "Cardinal Health", Sector: "Health Care", Symbol: "CAH" },
  { label: "CarMax", Sector: "Consumer Discretionary", Symbol: "KMX" },
  {
    label: "Carnival Corporation",
    Sector: "Consumer Discretionary",
    Symbol: "CCL",
  },
  { label: "Carrier Global", Sector: "Industrials", Symbol: "CARR" },
  { label: "Catalent", Sector: "Health Care", Symbol: "CTLT" },
  { label: "Caterpillar", Sector: "Industrials", Symbol: "CAT" },
  { label: "Cboe Global Markets", Sector: "Financials", Symbol: "CBOE" },
  { label: "CBRE", Sector: "Real Estate", Symbol: "CBRE" },
  { label: "CDW", Sector: "Information Technology", Symbol: "CDW" },
  { label: "Celanese", Sector: "Materials", Symbol: "CE" },
  { label: "Centene Corporation", Sector: "Health Care", Symbol: "CNC" },
  { label: "CenterPoint Energy", Sector: "Utilities", Symbol: "CNP" },
  { label: "Ceridian", Sector: "Information Technology", Symbol: "CDAY" },
  { label: "Cerner", Sector: "Health Care", Symbol: "CERN" },
  { label: "CF Industries", Sector: "Materials", Symbol: "CF" },
  { label: "Charles River Laboratories", Sector: "Health Care", Symbol: "CRL" },
  { label: "Charles Schwab Corporation", Sector: "Financials", Symbol: "SCHW" },
  {
    label: "Charter Communications",
    Sector: "Communication Services",
    Symbol: "CHTR",
  },
  { label: "Chevron Corporation", Sector: "Energy", Symbol: "CVX" },
  {
    label: "Chipotle Mexican Grill",
    Sector: "Consumer Discretionary",
    Symbol: "CMG",
  },
  { label: "Chubb", Sector: "Financials", Symbol: "CB" },
  { label: "Church & Dwight", Sector: "Consumer Staples", Symbol: "CHD" },
  { label: "Cigna", Sector: "Health Care", Symbol: "CI" },
  { label: "Cincinnati Financial", Sector: "Financials", Symbol: "CINF" },
  { label: "Cintas Corporation", Sector: "Industrials", Symbol: "CTAS" },
  { label: "Cisco Systems", Sector: "Information Technology", Symbol: "CSCO" },
  { label: "Citigroup", Sector: "Financials", Symbol: "C" },
  { label: "Citizens Financial Group", Sector: "Financials", Symbol: "CFG" },
  { label: "Citrix Systems", Sector: "Information Technology", Symbol: "CTXS" },
  { label: "Clorox", Sector: "Consumer Staples", Symbol: "CLX" },
  { label: "CME Group", Sector: "Financials", Symbol: "CME" },
  { label: "CMS Energy", Sector: "Utilities", Symbol: "CMS" },
  { label: "Coca-Cola Company", Sector: "Consumer Staples", Symbol: "KO" },
  {
    label: "Cognizant Technology Solutions",
    Sector: "Information Technology",
    Symbol: "CTSH",
  },
  { label: "Colgate-Palmolive", Sector: "Consumer Staples", Symbol: "CL" },
  { label: "Comcast", Sector: "Communication Services", Symbol: "CMCSA" },
  { label: "Comerica", Sector: "Financials", Symbol: "CMA" },
  { label: "Conagra Brands", Sector: "Consumer Staples", Symbol: "CAG" },
  { label: "ConocoPhillips", Sector: "Energy", Symbol: "COP" },
  { label: "Consolidated Edison", Sector: "Utilities", Symbol: "ED" },
  { label: "Constellation Brands", Sector: "Consumer Staples", Symbol: "STZ" },
  { label: "Copart", Sector: "Industrials", Symbol: "CPRT" },
  { label: "Corning", Sector: "Information Technology", Symbol: "GLW" },
  { label: "Corteva", Sector: "Materials", Symbol: "CTVA" },
  { label: "Costco", Sector: "Consumer Staples", Symbol: "COST" },
  { label: "Coterra", Sector: "Energy", Symbol: "CTRA" },
  { label: "Crown Castle", Sector: "Real Estate", Symbol: "CCI" },
  { label: "CSX", Sector: "Industrials", Symbol: "CSX" },
  { label: "Cummins", Sector: "Industrials", Symbol: "CMI" },
  { label: "CVS Health", Sector: "Health Care", Symbol: "CVS" },
  { label: "D. R. Horton", Sector: "Consumer Discretionary", Symbol: "DHI" },
  { label: "Danaher Corporation", Sector: "Health Care", Symbol: "DHR" },
  {
    label: "Darden Restaurants",
    Sector: "Consumer Discretionary",
    Symbol: "DRI",
  },
  { label: "DaVita", Sector: "Health Care", Symbol: "DVA" },
  { label: "Deere & Co.", Sector: "Industrials", Symbol: "DE" },
  { label: "Delta Air Lines", Sector: "Industrials", Symbol: "DAL" },
  { label: "Dentsply Sirona", Sector: "Health Care", Symbol: "XRAY" },
  { label: "Devon Energy", Sector: "Energy", Symbol: "DVN" },
  { label: "DexCom", Sector: "Health Care", Symbol: "DXCM" },
  { label: "Diamondback Energy", Sector: "Energy", Symbol: "FANG" },
  { label: "Digital Realty Trust", Sector: "Real Estate", Symbol: "DLR" },
  { label: "Discover Financial Services", Sector: "Financials", Symbol: "DFS" },
  {
    label: "Discovery (Series A)",
    Sector: "Communication Services",
    Symbol: "DISCA",
  },
  {
    label: "Discovery (Series C)",
    Sector: "Communication Services",
    Symbol: "DISCK",
  },
  { label: "Dish Network", Sector: "Communication Services", Symbol: "DISH" },
  { label: "Dollar General", Sector: "Consumer Discretionary", Symbol: "DG" },
  { label: "Dollar Tree", Sector: "Consumer Discretionary", Symbol: "DLTR" },
  { label: "Dominion Energy", Sector: "Utilities", Symbol: "D" },
  { label: "Domino's Pizza", Sector: "Consumer Discretionary", Symbol: "DPZ" },
  { label: "Dover Corporation", Sector: "Industrials", Symbol: "DOV" },
  { label: "Dow", Sector: "Materials", Symbol: "DOW" },
  { label: "DTE Energy", Sector: "Utilities", Symbol: "DTE" },
  { label: "Duke Energy", Sector: "Utilities", Symbol: "DUK" },
  { label: "Duke Realty Corp", Sector: "Real Estate", Symbol: "DRE" },
  { label: "DuPont", Sector: "Materials", Symbol: "DD" },
  { label: "DXC Technology", Sector: "Information Technology", Symbol: "DXC" },
  { label: "Eastman Chemical", Sector: "Materials", Symbol: "EMN" },
  { label: "Eaton Corporation", Sector: "Industrials", Symbol: "ETN" },
  { label: "eBay", Sector: "Consumer Discretionary", Symbol: "EBAY" },
  { label: "Ecolab", Sector: "Materials", Symbol: "ECL" },
  { label: "Edison International", Sector: "Utilities", Symbol: "EIX" },
  { label: "Edwards Lifesciences", Sector: "Health Care", Symbol: "EW" },
  { label: "Electronic Arts", Sector: "Communication Services", Symbol: "EA" },
  { label: "Eli Lilly & Co", Sector: "Health Care", Symbol: "LLY" },
  { label: "Emerson Electric Company", Sector: "Industrials", Symbol: "EMR" },
  { label: "Enphase Energy", Sector: "Information Technology", Symbol: "ENPH" },
  { label: "Entergy", Sector: "Utilities", Symbol: "ETR" },
  { label: "EOG Resources", Sector: "Energy", Symbol: "EOG" },
  { label: "Equifax", Sector: "Industrials", Symbol: "EFX" },
  { label: "Equinix", Sector: "Real Estate", Symbol: "EQIX" },
  { label: "Equity Residential", Sector: "Real Estate", Symbol: "EQR" },
  { label: "Essex Property Trust", Sector: "Real Estate", Symbol: "ESS" },
  {
    label: "Est\u00e9e Lauder Companies",
    Sector: "Consumer Staples",
    Symbol: "EL",
  },
  { label: "Etsy", Sector: "Consumer Discretionary", Symbol: "ETSY" },
  { label: "Everest Re", Sector: "Financials", Symbol: "RE" },
  { label: "Evergy", Sector: "Utilities", Symbol: "EVRG" },
  { label: "Eversource Energy", Sector: "Utilities", Symbol: "ES" },
  { label: "Exelon", Sector: "Utilities", Symbol: "EXC" },
  { label: "Expedia Group", Sector: "Consumer Discretionary", Symbol: "EXPE" },
  { label: "Expeditors", Sector: "Industrials", Symbol: "EXPD" },
  { label: "Extra Space Storage", Sector: "Real Estate", Symbol: "EXR" },
  { label: "ExxonMobil", Sector: "Energy", Symbol: "XOM" },
  { label: "F5 Networks", Sector: "Information Technology", Symbol: "FFIV" },
  { label: "Facebook", Sector: "Communication Services", Symbol: "FB" },
  { label: "Fastenal", Sector: "Industrials", Symbol: "FAST" },
  {
    label: "Federal Realty Investment Trust",
    Sector: "Real Estate",
    Symbol: "FRT",
  },
  { label: "FedEx", Sector: "Industrials", Symbol: "FDX" },
  {
    label: "Fidelity National Information Services",
    Sector: "Information Technology",
    Symbol: "FIS",
  },
  { label: "Fifth Third Bancorp", Sector: "Financials", Symbol: "FITB" },
  { label: "First Republic Bank", Sector: "Financials", Symbol: "FRC" },
  { label: "FirstEnergy", Sector: "Utilities", Symbol: "FE" },
  { label: "Fiserv", Sector: "Information Technology", Symbol: "FISV" },
  { label: "Fleetcor", Sector: "Information Technology", Symbol: "FLT" },
  { label: "FMC Corporation", Sector: "Materials", Symbol: "FMC" },
  { label: "Ford", Sector: "Consumer Discretionary", Symbol: "F" },
  { label: "Fortinet", Sector: "Information Technology", Symbol: "FTNT" },
  { label: "Fortive", Sector: "Industrials", Symbol: "FTV" },
  {
    label: "Fortune Brands Home & Security",
    Sector: "Industrials",
    Symbol: "FBHS",
  },
  {
    label: "Fox Corporation (Class A)",
    Sector: "Communication Services",
    Symbol: "FOXA",
  },
  {
    label: "Fox Corporation (Class B)",
    Sector: "Communication Services",
    Symbol: "FOX",
  },
  { label: "Franklin Resources", Sector: "Financials", Symbol: "BEN" },
  { label: "Freeport-McMoRan", Sector: "Materials", Symbol: "FCX" },
  { label: "Gap", Sector: "Consumer Discretionary", Symbol: "GPS" },
  { label: "Garmin", Sector: "Consumer Discretionary", Symbol: "GRMN" },
  { label: "Gartner", Sector: "Information Technology", Symbol: "IT" },
  { label: "Generac Holdings", Sector: "Industrials", Symbol: "GNRC" },
  { label: "General Dynamics", Sector: "Industrials", Symbol: "GD" },
  { label: "General Electric", Sector: "Industrials", Symbol: "GE" },
  { label: "General Mills", Sector: "Consumer Staples", Symbol: "GIS" },
  { label: "General Motors", Sector: "Consumer Discretionary", Symbol: "GM" },
  { label: "Genuine Parts", Sector: "Consumer Discretionary", Symbol: "GPC" },
  { label: "Gilead Sciences", Sector: "Health Care", Symbol: "GILD" },
  { label: "Global Payments", Sector: "Information Technology", Symbol: "GPN" },
  { label: "Globe Life", Sector: "Financials", Symbol: "GL" },
  { label: "Goldman Sachs", Sector: "Financials", Symbol: "GS" },
  { label: "Halliburton", Sector: "Energy", Symbol: "HAL" },
  { label: "Hanesbrands", Sector: "Consumer Discretionary", Symbol: "HBI" },
  { label: "Hasbro", Sector: "Consumer Discretionary", Symbol: "HAS" },
  { label: "HCA Healthcare", Sector: "Health Care", Symbol: "HCA" },
  { label: "Healthpeak Properties", Sector: "Real Estate", Symbol: "PEAK" },
  { label: "Henry Schein", Sector: "Health Care", Symbol: "HSIC" },
  { label: "Hess Corporation", Sector: "Energy", Symbol: "HES" },
  {
    label: "Hewlett Packard Enterprise",
    Sector: "Information Technology",
    Symbol: "HPE",
  },
  { label: "Hilton Worldwide", Sector: "Consumer Discretionary", Symbol: "HLT" },
  { label: "Hologic", Sector: "Health Care", Symbol: "HOLX" },
  { label: "Home Depot", Sector: "Consumer Discretionary", Symbol: "HD" },
  { label: "Honeywell", Sector: "Industrials", Symbol: "HON" },
  { label: "Hormel", Sector: "Consumer Staples", Symbol: "HRL" },
  { label: "Host Hotels & Resorts", Sector: "Real Estate", Symbol: "HST" },
  { label: "Howmet Aerospace", Sector: "Industrials", Symbol: "HWM" },
  { label: "HP", Sector: "Information Technology", Symbol: "HPQ" },
  { label: "Humana", Sector: "Health Care", Symbol: "HUM" },
  { label: "Huntington Bancshares", Sector: "Financials", Symbol: "HBAN" },
  {
    label: "Huntington Ingalls Industries",
    Sector: "Industrials",
    Symbol: "HII",
  },
  { label: "IBM", Sector: "Information Technology", Symbol: "IBM" },
  { label: "IDEX Corporation", Sector: "Industrials", Symbol: "IEX" },
  { label: "Idexx Laboratories", Sector: "Health Care", Symbol: "IDXX" },
  { label: "IHS Markit", Sector: "Industrials", Symbol: "INFO" },
  { label: "Illinois Tool Works", Sector: "Industrials", Symbol: "ITW" },
  { label: "Illumina", Sector: "Health Care", Symbol: "ILMN" },
  { label: "Incyte", Sector: "Health Care", Symbol: "INCY" },
  { label: "Ingersoll Rand", Sector: "Industrials", Symbol: "IR" },
  { label: "Intel", Sector: "Information Technology", Symbol: "INTC" },
  { label: "Intercontinental Exchange", Sector: "Financials", Symbol: "ICE" },
  {
    label: "International Flavors & Fragrances",
    Sector: "Materials",
    Symbol: "IFF",
  },
  { label: "International Paper", Sector: "Materials", Symbol: "IP" },
  {
    label: "Interpublic Group",
    Sector: "Communication Services",
    Symbol: "IPG",
  },
  { label: "Intuit", Sector: "Information Technology", Symbol: "INTU" },
  { label: "Intuitive Surgical", Sector: "Health Care", Symbol: "ISRG" },
  { label: "Invesco", Sector: "Financials", Symbol: "IVZ" },
  { label: "IPG Photonics", Sector: "Information Technology", Symbol: "IPGP" },
  { label: "IQVIA", Sector: "Health Care", Symbol: "IQV" },
  { label: "Iron Mountain", Sector: "Real Estate", Symbol: "IRM" },
  { label: "J. B. Hunt", Sector: "Industrials", Symbol: "JBHT" },
  {
    label: "Jack Henry & Associates",
    Sector: "Information Technology",
    Symbol: "JKHY",
  },
  { label: "Jacobs Engineering Group", Sector: "Industrials", Symbol: "J" },
  { label: "JM Smucker", Sector: "Consumer Staples", Symbol: "SJM" },
  { label: "Johnson & Johnson", Sector: "Health Care", Symbol: "JNJ" },
  { label: "Johnson Controls", Sector: "Industrials", Symbol: "JCI" },
  { label: "JPMorgan Chase", Sector: "Financials", Symbol: "JPM" },
  {
    label: "Juniper Networks",
    Sector: "Information Technology",
    Symbol: "JNPR",
  },
  { label: "Kansas City Southern", Sector: "Industrials", Symbol: "KSU" },
  { label: "Kellogg's", Sector: "Consumer Staples", Symbol: "K" },
  { label: "KeyCorp", Sector: "Financials", Symbol: "KEY" },
  {
    label: "Keysight Technologies",
    Sector: "Information Technology",
    Symbol: "KEYS",
  },
  { label: "Kimberly-Clark", Sector: "Consumer Staples", Symbol: "KMB" },
  { label: "Kimco Realty", Sector: "Real Estate", Symbol: "KIM" },
  { label: "Kinder Morgan", Sector: "Energy", Symbol: "KMI" },
  { label: "KLA Corporation", Sector: "Information Technology", Symbol: "KLAC" },
  { label: "Kraft Heinz", Sector: "Consumer Staples", Symbol: "KHC" },
  { label: "Kroger", Sector: "Consumer Staples", Symbol: "KR" },
  { label: "L3Harris Technologies", Sector: "Industrials", Symbol: "LHX" },
  { label: "LabCorp", Sector: "Health Care", Symbol: "LH" },
  { label: "Lam Research", Sector: "Information Technology", Symbol: "LRCX" },
  { label: "Lamb Weston", Sector: "Consumer Staples", Symbol: "LW" },
  { label: "Las Vegas Sands", Sector: "Consumer Discretionary", Symbol: "LVS" },
  { label: "Leggett & Platt", Sector: "Consumer Discretionary", Symbol: "LEG" },
  { label: "Leidos", Sector: "Industrials", Symbol: "LDOS" },
  { label: "Lennar", Sector: "Consumer Discretionary", Symbol: "LEN" },
  { label: "Lincoln National", Sector: "Financials", Symbol: "LNC" },
  { label: "Linde", Sector: "Materials", Symbol: "LIN" },
  {
    label: "Live Nation Entertainment",
    Sector: "Communication Services",
    Symbol: "LYV",
  },
  { label: "LKQ Corporation", Sector: "Consumer Discretionary", Symbol: "LKQ" },
  { label: "Lockheed Martin", Sector: "Industrials", Symbol: "LMT" },
  { label: "Loews Corporation", Sector: "Financials", Symbol: "L" },
  { label: "Lowe's", Sector: "Consumer Discretionary", Symbol: "LOW" },
  {
    label: "Lumen Technologies",
    Sector: "Communication Services",
    Symbol: "LUMN",
  },
  { label: "LyondellBasell", Sector: "Materials", Symbol: "LYB" },
  { label: "M&T Bank", Sector: "Financials", Symbol: "MTB" },
  { label: "Marathon Oil", Sector: "Energy", Symbol: "MRO" },
  { label: "Marathon Petroleum", Sector: "Energy", Symbol: "MPC" },
  { label: "MarketAxess", Sector: "Financials", Symbol: "MKTX" },
  {
    label: "Marriott International",
    Sector: "Consumer Discretionary",
    Symbol: "MAR",
  },
  { label: "Marsh & McLennan", Sector: "Financials", Symbol: "MMC" },
  { label: "Martin Marietta Materials", Sector: "Materials", Symbol: "MLM" },
  { label: "Masco", Sector: "Industrials", Symbol: "MAS" },
  { label: "Mastercard", Sector: "Information Technology", Symbol: "MA" },
  { label: "Match Group", Sector: "Communication Services", Symbol: "MTCH" },
  { label: "McCormick & Company", Sector: "Consumer Staples", Symbol: "MKC" },
  { label: "McDonald's", Sector: "Consumer Discretionary", Symbol: "MCD" },
  { label: "McKesson Corporation", Sector: "Health Care", Symbol: "MCK" },
  { label: "Medtronic", Sector: "Health Care", Symbol: "MDT" },
  { label: "Merck & Co.", Sector: "Health Care", Symbol: "MRK" },
  { label: "MetLife", Sector: "Financials", Symbol: "MET" },
  { label: "Mettler Toledo", Sector: "Health Care", Symbol: "MTD" },
  {
    label: "MGM Resorts International",
    Sector: "Consumer Discretionary",
    Symbol: "MGM",
  },
  {
    label: "Microchip Technology",
    Sector: "Information Technology",
    Symbol: "MCHP",
  },
  { label: "Micron Technology", Sector: "Information Technology", Symbol: "MU" },
  { label: "Microsoft", Sector: "Information Technology", Symbol: "MSFT" },
  { label: "Mid-America Apartments", Sector: "Real Estate", Symbol: "MAA" },
  { label: "Moderna", Sector: "Health Care", Symbol: "MRNA" },
  {
    label: "Mohawk Industries",
    Sector: "Consumer Discretionary",
    Symbol: "MHK",
  },
  {
    label: "Molson Coors Beverage Company",
    Sector: "Consumer Staples",
    Symbol: "TAP",
  },
  {
    label: "Mondelez International",
    Sector: "Consumer Staples",
    Symbol: "MDLZ",
  },
  {
    label: "Monolithic Power Systems",
    Sector: "Information Technology",
    Symbol: "MPWR",
  },
  { label: "Monster Beverage", Sector: "Consumer Staples", Symbol: "MNST" },
  { label: "Moody's Corporation", Sector: "Financials", Symbol: "MCO" },
  { label: "Morgan Stanley", Sector: "Financials", Symbol: "MS" },
  {
    label: "Motorola Solutions",
    Sector: "Information Technology",
    Symbol: "MSI",
  },
  { label: "MSCI", Sector: "Financials", Symbol: "MSCI" },
  { label: "Nasdaq", Sector: "Financials", Symbol: "NDAQ" },
  { label: "NetApp", Sector: "Information Technology", Symbol: "NTAP" },
  { label: "Netflix", Sector: "Communication Services", Symbol: "NFLX" },
  { label: "Newell Brands", Sector: "Consumer Discretionary", Symbol: "NWL" },
  { label: "Newmont", Sector: "Materials", Symbol: "NEM" },
  {
    label: "News Corp (Class A)",
    Sector: "Communication Services",
    Symbol: "NWSA",
  },
  {
    label: "News Corp (Class B)",
    Sector: "Communication Services",
    Symbol: "NWS",
  },
  { label: "NextEra Energy", Sector: "Utilities", Symbol: "NEE" },
  { label: "Nielsen Holdings", Sector: "Industrials", Symbol: "NLSN" },
  { label: "Nike", Sector: "Consumer Discretionary", Symbol: "NKE" },
  { label: "NiSource", Sector: "Utilities", Symbol: "NI" },
  { label: "Norfolk Southern", Sector: "Industrials", Symbol: "NSC" },
  { label: "Northern Trust", Sector: "Financials", Symbol: "NTRS" },
  { label: "Northrop Grumman", Sector: "Industrials", Symbol: "NOC" },
  { label: "NortonLifeLock", Sector: "Information Technology", Symbol: "NLOK" },
  {
    label: "Norwegian Cruise Line Holdings",
    Sector: "Consumer Discretionary",
    Symbol: "NCLH",
  },
  { label: "NRG Energy", Sector: "Utilities", Symbol: "NRG" },
  { label: "Nucor", Sector: "Materials", Symbol: "NUE" },
  { label: "Nvidia", Sector: "Information Technology", Symbol: "NVDA" },
  { label: "NVR", Sector: "Consumer Discretionary", Symbol: "NVR" },
  { label: "NXP", Sector: "Information Technology", Symbol: "NXPI" },
  {
    label: "O'Reilly Automotive",
    Sector: "Consumer Discretionary",
    Symbol: "ORLY",
  },
  { label: "Occidental Petroleum", Sector: "Energy", Symbol: "OXY" },
  { label: "Old Dominion Freight Line", Sector: "Industrials", Symbol: "ODFL" },
  { label: "Omnicom Group", Sector: "Communication Services", Symbol: "OMC" },
  { label: "Oneok", Sector: "Energy", Symbol: "OKE" },
  { label: "Oracle", Sector: "Information Technology", Symbol: "ORCL" },
  { label: "Organon & Co.", Sector: "Health Care", Symbol: "OGN" },
  { label: "Otis Worldwide", Sector: "Industrials", Symbol: "OTIS" },
  { label: "Paccar", Sector: "Industrials", Symbol: "PCAR" },
  {
    label: "Packaging Corporation of America",
    Sector: "Materials",
    Symbol: "PKG",
  },
  { label: "Parker-Hannifin", Sector: "Industrials", Symbol: "PH" },
  { label: "Paychex", Sector: "Information Technology", Symbol: "PAYX" },
  { label: "Paycom", Sector: "Information Technology", Symbol: "PAYC" },
  { label: "PayPal", Sector: "Information Technology", Symbol: "PYPL" },
  {
    label: "Penn National Gaming",
    Sector: "Consumer Discretionary",
    Symbol: "PENN",
  },
  { label: "Pentair", Sector: "Industrials", Symbol: "PNR" },
  { label: "People's United Financial", Sector: "Financials", Symbol: "PBCT" },
  { label: "PepsiCo", Sector: "Consumer Staples", Symbol: "PEP" },
  { label: "PerkinElmer", Sector: "Health Care", Symbol: "PKI" },
  { label: "Pfizer", Sector: "Health Care", Symbol: "PFE" },
  {
    label: "Philip Morris International",
    Sector: "Consumer Staples",
    Symbol: "PM",
  },
  { label: "Phillips 66", Sector: "Energy", Symbol: "PSX" },
  { label: "Pinnacle West Capital", Sector: "Utilities", Symbol: "PNW" },
  { label: "Pioneer Natural Resources", Sector: "Energy", Symbol: "PXD" },
  { label: "PNC Financial Services", Sector: "Financials", Symbol: "PNC" },
  {
    label: "Pool Corporation",
    Sector: "Consumer Discretionary",
    Symbol: "POOL",
  },
  { label: "PPG Industries", Sector: "Materials", Symbol: "PPG" },
  { label: "PPL", Sector: "Utilities", Symbol: "PPL" },
  { label: "Principal Financial Group", Sector: "Financials", Symbol: "PFG" },
  { label: "Procter & Gamble", Sector: "Consumer Staples", Symbol: "PG" },
  { label: "Progressive Corporation", Sector: "Financials", Symbol: "PGR" },
  { label: "Prologis", Sector: "Real Estate", Symbol: "PLD" },
  { label: "Prudential Financial", Sector: "Financials", Symbol: "PRU" },
  { label: "PTC", Sector: "Information Technology", Symbol: "PTC" },
  {
    label: "Public Service Enterprise Group",
    Sector: "Utilities",
    Symbol: "PEG",
  },
  { label: "Public Storage", Sector: "Real Estate", Symbol: "PSA" },
  { label: "PulteGroup", Sector: "Consumer Discretionary", Symbol: "PHM" },
  { label: "PVH", Sector: "Consumer Discretionary", Symbol: "PVH" },
  { label: "Qorvo", Sector: "Information Technology", Symbol: "QRVO" },
  { label: "Qualcomm", Sector: "Information Technology", Symbol: "QCOM" },
  { label: "Quanta Services", Sector: "Industrials", Symbol: "PWR" },
  { label: "Quest Diagnostics", Sector: "Health Care", Symbol: "DGX" },
  {
    label: "Ralph Lauren Corporation",
    Sector: "Consumer Discretionary",
    Symbol: "RL",
  },
  { label: "Raymond James Financial", Sector: "Financials", Symbol: "RJF" },
  { label: "Raytheon Technologies", Sector: "Industrials", Symbol: "RTX" },
  { label: "Realty Income Corporation", Sector: "Real Estate", Symbol: "O" },
  { label: "Regency Centers", Sector: "Real Estate", Symbol: "REG" },
  { label: "Regeneron Pharmaceuticals", Sector: "Health Care", Symbol: "REGN" },
  { label: "Regions Financial Corporation", Sector: "Financials", Symbol: "RF" },
  { label: "Republic Services", Sector: "Industrials", Symbol: "RSG" },
  { label: "ResMed", Sector: "Health Care", Symbol: "RMD" },
  { label: "Robert Half International", Sector: "Industrials", Symbol: "RHI" },
  { label: "Rockwell Automation", Sector: "Industrials", Symbol: "ROK" },
  { label: "Rollins", Sector: "Industrials", Symbol: "ROL" },
  { label: "Roper Technologies", Sector: "Industrials", Symbol: "ROP" },
  { label: "Ross Stores", Sector: "Consumer Discretionary", Symbol: "ROST" },
  {
    label: "Royal Caribbean Group",
    Sector: "Consumer Discretionary",
    Symbol: "RCL",
  },
  { label: "S&P Global", Sector: "Financials", Symbol: "SPGI" },
  { label: "Salesforce", Sector: "Information Technology", Symbol: "CRM" },
  { label: "SBA Communications", Sector: "Real Estate", Symbol: "SBAC" },
  { label: "Schlumberger", Sector: "Energy", Symbol: "SLB" },
  {
    label: "Seagate Technology",
    Sector: "Information Technology",
    Symbol: "STX",
  },
  { label: "Sealed Air", Sector: "Materials", Symbol: "SEE" },
  { label: "Sempra Energy", Sector: "Utilities", Symbol: "SRE" },
  { label: "ServiceNow", Sector: "Information Technology", Symbol: "NOW" },
  { label: "Sherwin-Williams", Sector: "Materials", Symbol: "SHW" },
  { label: "Simon Property Group", Sector: "Real Estate", Symbol: "SPG" },
  {
    label: "Skyworks Solutions",
    Sector: "Information Technology",
    Symbol: "SWKS",
  },
  { label: "Snap-on", Sector: "Industrials", Symbol: "SNA" },
  { label: "Southern Company", Sector: "Utilities", Symbol: "SO" },
  { label: "Southwest Airlines", Sector: "Industrials", Symbol: "LUV" },
  { label: "Stanley Black & Decker", Sector: "Industrials", Symbol: "SWK" },
  { label: "Starbucks", Sector: "Consumer Discretionary", Symbol: "SBUX" },
  { label: "State Street Corporation", Sector: "Financials", Symbol: "STT" },
  { label: "Steris", Sector: "Health Care", Symbol: "STE" },
  { label: "Stryker Corporation", Sector: "Health Care", Symbol: "SYK" },
  { label: "SVB Financial", Sector: "Financials", Symbol: "SIVB" },
  { label: "Synchrony Financial", Sector: "Financials", Symbol: "SYF" },
  { label: "Synopsys", Sector: "Information Technology", Symbol: "SNPS" },
  { label: "Sysco", Sector: "Consumer Staples", Symbol: "SYY" },
  { label: "T-Mobile US", Sector: "Communication Services", Symbol: "TMUS" },
  { label: "T. Rowe Price", Sector: "Financials", Symbol: "TROW" },
  {
    label: "Take-Two Interactive",
    Sector: "Communication Services",
    Symbol: "TTWO",
  },
  { label: "Tapestry", Sector: "Consumer Discretionary", Symbol: "TPR" },
  {
    label: "Target Corporation",
    Sector: "Consumer Discretionary",
    Symbol: "TGT",
  },
  { label: "TE Connectivity", Sector: "Information Technology", Symbol: "TEL" },
  { label: "Teledyne Technologies", Sector: "Industrials", Symbol: "TDY" },
  { label: "Teleflex", Sector: "Health Care", Symbol: "TFX" },
  { label: "Teradyne", Sector: "Information Technology", Symbol: "TER" },
  { label: "Tesla", Sector: "Consumer Discretionary", Symbol: "TSLA" },
  {
    label: "Texas Instruments",
    Sector: "Information Technology",
    Symbol: "TXN",
  },
  { label: "Textron", Sector: "Industrials", Symbol: "TXT" },
  { label: "The Cooper Companies", Sector: "Health Care", Symbol: "COO" },
  { label: "The Hartford", Sector: "Financials", Symbol: "HIG" },
  { label: "The Hershey Company", Sector: "Consumer Staples", Symbol: "HSY" },
  { label: "The Mosaic Company", Sector: "Materials", Symbol: "MOS" },
  { label: "The Travelers Companies", Sector: "Financials", Symbol: "TRV" },
  {
    label: "The Walt Disney Company",
    Sector: "Communication Services",
    Symbol: "DIS",
  },
  { label: "Thermo Fisher Scientific", Sector: "Health Care", Symbol: "TMO" },
  { label: "TJX Companies", Sector: "Consumer Discretionary", Symbol: "TJX" },
  {
    label: "Tractor Supply Company",
    Sector: "Consumer Discretionary",
    Symbol: "TSCO",
  },
  { label: "Trane Technologies", Sector: "Industrials", Symbol: "TT" },
  { label: "TransDigm Group", Sector: "Industrials", Symbol: "TDG" },
  { label: "Trimble", Sector: "Information Technology", Symbol: "TRMB" },
  { label: "Truist Financial", Sector: "Financials", Symbol: "TFC" },
  { label: "Twitter", Sector: "Communication Services", Symbol: "TWTR" },
  {
    label: "Tyler Technologies",
    Sector: "Information Technology",
    Symbol: "TYL",
  },
  { label: "Tyson Foods", Sector: "Consumer Staples", Symbol: "TSN" },
  { label: "U.S. Bancorp", Sector: "Financials", Symbol: "USB" },
  { label: "UDR", Sector: "Real Estate", Symbol: "UDR" },
  { label: "Ulta Beauty", Sector: "Consumer Discretionary", Symbol: "ULTA" },
  {
    label: "Under Armour (Class A)",
    Sector: "Consumer Discretionary",
    Symbol: "UAA",
  },
  {
    label: "Under Armour (Class C)",
    Sector: "Consumer Discretionary",
    Symbol: "UA",
  },
  { label: "Union Pacific", Sector: "Industrials", Symbol: "UNP" },
  { label: "United Airlines", Sector: "Industrials", Symbol: "UAL" },
  { label: "United Parcel Service", Sector: "Industrials", Symbol: "UPS" },
  { label: "United Rentals", Sector: "Industrials", Symbol: "URI" },
  { label: "UnitedHealth Group", Sector: "Health Care", Symbol: "UNH" },
  { label: "Universal Health Services", Sector: "Health Care", Symbol: "UHS" },
  { label: "Valero Energy", Sector: "Energy", Symbol: "VLO" },
  { label: "Ventas", Sector: "Real Estate", Symbol: "VTR" },
  { label: "Verisign", Sector: "Information Technology", Symbol: "VRSN" },
  { label: "Verisk Analytics", Sector: "Industrials", Symbol: "VRSK" },
  {
    label: "Verizon Communications",
    Sector: "Communication Services",
    Symbol: "VZ",
  },
  { label: "Vertex Pharmaceuticals", Sector: "Health Care", Symbol: "VRTX" },
  { label: "VF Corporation", Sector: "Consumer Discretionary", Symbol: "VFC" },
  { label: "ViacomCBS", Sector: "Communication Services", Symbol: "VIAC" },
  { label: "Viatris", Sector: "Health Care", Symbol: "VTRS" },
  { label: "Visa", Sector: "Information Technology", Symbol: "V" },
  { label: "Vornado Realty Trust", Sector: "Real Estate", Symbol: "VNO" },
  { label: "Vulcan Materials", Sector: "Materials", Symbol: "VMC" },
  { label: "W. R. Berkley Corporation", Sector: "Financials", Symbol: "WRB" },
  { label: "W. W. Grainger", Sector: "Industrials", Symbol: "GWW" },
  { label: "Wabtec", Sector: "Industrials", Symbol: "WAB" },
  {
    label: "Walgreens Boots Alliance",
    Sector: "Consumer Staples",
    Symbol: "WBA",
  },
  { label: "Walmart", Sector: "Consumer Staples", Symbol: "WMT" },
  { label: "Waste Management", Sector: "Industrials", Symbol: "WM" },
  { label: "Waters Corporation", Sector: "Health Care", Symbol: "WAT" },
  { label: "WEC Energy Group", Sector: "Utilities", Symbol: "WEC" },
  { label: "Wells Fargo", Sector: "Financials", Symbol: "WFC" },
  { label: "Welltower", Sector: "Real Estate", Symbol: "WELL" },
  {
    label: "West Pharmaceutical Services",
    Sector: "Health Care",
    Symbol: "WST",
  },
  { label: "Western Digital", Sector: "Information Technology", Symbol: "WDC" },
  { label: "Western Union", Sector: "Information Technology", Symbol: "WU" },
  { label: "WestRock", Sector: "Materials", Symbol: "WRK" },
  { label: "Weyerhaeuser", Sector: "Real Estate", Symbol: "WY" },
  {
    label: "Whirlpool Corporation",
    Sector: "Consumer Discretionary",
    Symbol: "WHR",
  },
  { label: "Williams Companies", Sector: "Energy", Symbol: "WMB" },
  { label: "Willis Towers Watson", Sector: "Financials", Symbol: "WLTW" },
  { label: "Wynn Resorts", Sector: "Consumer Discretionary", Symbol: "WYNN" },
  { label: "Xcel Energy", Sector: "Utilities", Symbol: "XEL" },
  { label: "Xilinx", Sector: "Information Technology", Symbol: "XLNX" },
  { label: "Xylem", Sector: "Industrials", Symbol: "XYL" },
  { label: "Yum! Brands", Sector: "Consumer Discretionary", Symbol: "YUM" },
  {
    label: "Zebra Technologies",
    Sector: "Information Technology",
    Symbol: "ZBRA",
  },
  { label: "Zimmer Biomet", Sector: "Health Care", Symbol: "ZBH" },
  { label: "Zions Bancorp", Sector: "Financials", Symbol: "ZION" },
  { label: "Zoetis", Sector: "Health Care", Symbol: "ZTS" },
];
